# Generated by Django 4.0.4 on 2022-08-19 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orderen', '0001_initial'),
        ('sauce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sauceorden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderen_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderen.orderen')),
                ('sauces_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sauce.sauce')),
            ],
        ),
    ]
