# Generated by Django 4.0.4 on 2022-08-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saucesorden', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sauceorden',
            old_name='orderen_id',
            new_name='orderen',
        ),
        migrations.RenameField(
            model_name='sauceorden',
            old_name='sauces_id',
            new_name='sauces',
        ),
    ]
