# Generated by Django 4.0.4 on 2022-08-19 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_sauces'),
        ('saucesorden', '0002_rename_orderen_id_sauceorden_orderen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sauceorden',
            name='orderen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
