# Generated by Django 4.0.4 on 2022-08-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saucesorden', '0003_alter_sauceorden_orderen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sauceorden',
            old_name='orderen',
            new_name='order',
        ),
    ]
