# Generated by Django 4.0.4 on 2022-09-14 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saucesproduct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sauceproduct',
            name='namesauce',
        ),
    ]
