# Generated by Django 4.0.4 on 2022-09-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saucesproduct', '0002_remove_sauceproduct_namesauce'),
    ]

    operations = [
        migrations.AddField(
            model_name='sauceproduct',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
