# Generated by Django 3.2.16 on 2023-07-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeOrders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltypes',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='historicaltypes',
            name='code',
            field=models.CharField(max_length=2, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='historicaltypes',
            name='name',
            field=models.CharField(max_length=9, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='types',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='types',
            name='code',
            field=models.CharField(max_length=2, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='types',
            name='name',
            field=models.CharField(max_length=9, verbose_name='Nombre'),
        ),
    ]
