# Generated by Django 4.0.4 on 2022-08-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauce', '0001_initial'),
        ('orders', '0005_alter_order_sauces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sauces',
            field=models.ManyToManyField(blank=True, to='sauce.sauce'),
        ),
    ]
