# Generated by Django 4.0.4 on 2022-08-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesmans', '0001_initial'),
        ('orders', '0009_order_delivered_at_order_discount_order_prepared_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderen',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesmans.salesman'),
        ),
    ]
