# Generated by Django 4.0.4 on 2022-08-13 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesmans', '0001_initial'),
        ('orders', '0010_alter_orderen_salesman'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesmans.salesman'),
        ),
        migrations.AddField(
            model_name='order',
            name='salestax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='order',
            name='shipto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='order',
            name='tipo',
            field=models.CharField(choices=[('DM', 'Domicilio'), ('MS', 'Mesa'), ('LL', 'Llevar')], default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Orderen',
        ),
    ]
