# Generated by Django 4.0.4 on 2022-08-16 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderen', '0001_initial'),
        ('orders', '0011_order_number_order_salesman_order_salestax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orderen.orderen'),
        ),
    ]
