# Generated by Django 4.0.4 on 2022-08-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_orderen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sauces',
        ),
    ]
