# Generated by Django 4.0.4 on 2022-10-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_usertemp_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tipo',
            field=models.CharField(blank=True, choices=[('DM', 'Domicilio'), ('MS', 'Mesa'), ('LL', 'Llevar')], max_length=100, null=True),
        ),
    ]
